apiVersion: v1
kind: Service
metadata:
  name: zero-trust-app
  namespace: zero-trust
spec:
  type: NodePort
  selector:
    app: zero-trust-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080